server {
    listen 80;
    listen [::]:80;
    server_name 103.103.23.184 lapangin.id www.lapangin.id;

    root /var/www/lapangin.id;
    index index.html;

    location / {
        try_files $uri $uri/ /index.html;
    }

    location ~* \.(?:css|js|jpg|jpeg|gif|png|svg|ico|webp)$ {
        expires 7d;
        add_header Cache-Control "public, max-age=604800";
    }
}
